<?php

return [
    '3ème C' => 'Mme KOUMAKO',
    '3ème D' => 'Mr KONDI',
    '3ème B' => 'Mme BISSALOUWE',
    '3ème E' => 'Mr AGBEMEBIO',
    '3ème A' => 'Mr OURO-TAGBA',
    '4ème A' => 'Mr AVEGAN',
    '4ème B' => 'Mr de SOUZA',
    '4ème C' => 'Mr AMEGNONA',
    '4ème D' => 'Mr KOLANI',
    '5ème A' => 'Mr YOMBO',
    '5ème B' => 'Mme KASSOTE',
    '5ème C' => 'Mme KPELI-POUKPESSI',
    '5ème D' => 'Mr KERIM',
    '6ème A' => 'Mr OGBONE',
    '6ème B' => 'Mr DOLOU',
    '6ème C' => 'Mme KEGBENA',
    '6ème D' => 'Mr MINDIZINA',
    '2nd A4-1' => 'Mr NEBADI',
    '2nd A4-2' => 'Mr DJIGUI',
    '2nd CD'   => 'Mr ZABOUH',
    '1ère A4-1'=> 'Mme TCHAKOUN',
    '1ère A4-2'=> 'Mme TAKASSI',
    '1ere D4'  => 'Mr LAMBONI',
    'Tle D4-1' => 'Mr OUDANE',
    'Tle D4-2' => 'Mme KOSSI',
    'Tle A4-1' => 'Mr POTCHOWAÏ',
    'Tle A4-2' => 'Mr GOTA',
];
