<?php

/* return [
    '3ème C' => 'Mme KOUMAKO',
    '3ème D' => 'Mr KONDI',
    '3ème B' => 'Mme BISSALOUWE',
    '3ème E' => 'Mr AGBEMEBIO',
    '3ème A' => 'Mr OURO-TAGBA',
    '4ème A' => 'Mr AVEGAN',
    '4ème B' => 'Mr de SOUZA',
    '4ème C' => 'Mr AMEGNONA',
    '4ème D' => 'Mr KOLANI',
    '5ème A' => 'Mr YOMBO',
    '5ème B' => 'Mme KASSOTE',
    '5ème C' => 'Mme KPELI-POUKPESSI',
    '5ème D' => 'Mr KERIM',
    '6ème A' => 'Mr OGBONE',
    '6ème B' => 'Mr DOLOU',
    '6ème C' => 'Mme KEGBENA',
    '6ème D' => 'Mr MINDIZINA',
    '2nd A4-1' => 'Mr NEBADI',
    '2nd A4-2' => 'Mr DJIGUI',
    '2nd CD'   => 'Mr ZABOUH',
    '1ère A4-1'=> 'Mme TCHAKOUN',
    '1ère A4-2'=> 'Mme TAKASSI',
    '1ere D4'  => 'Mr LAMBONI',
    'Tle D4-1' => 'Mr OUDANE',
    'Tle D4-2' => 'Mme KOSSI',
    'Tle A4-1' => 'Mr POTCHOWAÏ',
    'Tle A4-2' => 'Mr GOTA',
]; prof principaux 2024-2025*/

return [
            '3ème C' => 'Mme TAKASSI',
            '3ème D' => 'Mr OGBONE',
            '3ème B' => 'Mme KOUMAKO',
            '3ème E' => 'Mr AGBEMEBIO',
            '3ème A' => 'Mr OURO-TAGBA',
            '4ème A' => 'Mme KEGBENA',
            '4ème B' => 'Mr KERIM',
            '4ème C' => 'Mme KIDIYO',
            //'4ème D' => 'Mr KOLANI',
            '5ème A' => 'Mr YOMBO',
            '5ème B' => 'Mr KOSSI',
            '5ème C' => 'Mr ABLIMI',
            '5ème D' => 'Mme BISSALOUWE',
            '6ème A' => 'Mme KPELI-POUKPEZI',
            '6ème B' => 'Mr MINDIZINA',
            '6ème C' => 'Mr AMEGNONA',
            '6ème D' => 'Mme KASSOTE',
            '2nd A4-1' => 'Mr GOTA',
            '2nd A4-2' => 'Mr KOLANI',
            '2nd CD' => 'Mr OUDANE',
            '1ère A4-1' => 'Mr NEBADI',
            '1ère A4-2' => 'Mr DJIGUI',
            '1ère A4-3' => 'Mme TCHAKOUN',
            '1ere D4' => 'Mr de SOUZA',
            'Tle D4-1' => 'Mr ZABOUH',
            'Tle D4-2' => 'Mme KOSSI',
            'Tle A4-1' => 'Mr POTCHOWAÏ',
            'Tle A4-2' => 'Mr BOKO',
        ];//prof principaux 2025-2026
